### ISSUE TITLE
example repo

### ISSUE THREAD

**Issue by noahehall** [rudxde/lerna-dockerize#43]
do you have a working example repo ?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaRedM** [comment]
Hey,
inside of the project you can find multiple example projects [here (/test/integration)](https://github.com/rudxde/lerna-dockerize/tree/master/packages/lerna-dockerize/test/integration).

Each directory contains a file named `Dockerfile.expected` which is the generated output of `lerna-dockerize`.

**Comment by rudxde** [comment]
I hope the answer was helpful, i will close this issue. If you have further questions please reopen or create an new issue.
