### ISSUE TITLE
When used with distroless or any other image not from dockerhub wrong Dockerfile generated

### ISSUE THREAD

**Issue by Mistic92** [rudxde/lerna-dockerize#53]
**Describe the bug**
We are using distroless image as prod base image. When used with command ```npx lerna-dockerize --template-dockerfile-name Dockerfile.template``` it generate Dockerfile with image value as ```FROM gcr as microservice-starter-1```

**To Reproduce**
1. Create file Dockerfile.template
```
FROM base as build
COPY ./package.json ./
RUN npm ci
RUN --if-exists npm run build
RUN rm -rf node_modules
RUN --if-exists npm ci --only=production

FROM gcr.io/distroless/nodejs as prod
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist /usr/src/app/dist
COPY --from=build /usr/src/app/node_modules /usr/src/app/node_modules
COPY _proto /usr/_proto
ENV NODE_ENV production
# ENV GRPC_TRACE all
ENV GRPC_VERBOSITY WARNING
CMD ["dist/main.js"]
```
and simple base image. 

2. Run ```npx lerna-dockerize --template-dockerfile-name Dockerfile.template```
3. Result Dockerfile contains bad code with only ```gcr``` instead of full url
```
RUN npm ci --only=production
FROM gcr as microservice-starter-1
WORKDIR /app/microservices/_microservice_template
```

**Comment by rudxde** [comment]
The issue should be resolved inside the 0.5.0 release, you can test a pre-release under the tag `0.5.0-build.7e0486a.0`.

```
npm i lerna-dockerize@0.5.0-build.7e0486a.0
```
