### ISSUE TITLE
Error when docker build: lerna ERR! FILTER No packages remain after filtering [ 'a' ]

### ISSUE THREAD

**Issue by xzdwq** [rudxde/lerna-dockerize#866]
I use the project from the examples: [https://github.com/rudxde/lerna-dockerize/tree/master/packages/lerna-dockerize/test/integration/simple](https://github.com/rudxde/lerna-dockerize/tree/master/packages/lerna-dockerize/test/integration/simple)

**Desktop:**
 - OS: Windows 10
 - Node v.16.13.1
 - Docker v.20.10.5

**To Reproduce**
Running commands: 
1. `npm i && lerna bootstrap`  
2. `npx lerna-dockerize init`
3. `npm run lerna-dockerize`  
4. `docker build -t test .`  

I get an error:
```bush
Step 9/35 : RUN npx lerna bootstrap --scope=a --includeDependencies
 ---> Running in d48c7eb76185
lerna notice cli v5.1.8
lerna notice filter including "a"
lerna notice filter including dependencies
lerna info filter [ 'a' ]
lerna ERR! EFILTER No packages remain after filtering [ 'a' ]
The command '/bin/sh -c npx lerna bootstrap --scope=a --includeDependencies' returned a non-zero code: 1
```
The example does not contain node dependencies, but even if you add packages to dependencies, the situation will not change. Most likely I'm doing something wrong, tell me the reason for my failure.

**Comment by rudxde** [comment]
Hi, thanks for your issue. There was a problem with the dockerfiles workdir in this (and other examples).

I have fixed the examples and the template from the init script to include the right workdir. They should work now as expected.

---

__Background:__

_Lerna dockerize expects the root workdir to be at `/app`, but in the node image it is `/`. Telling Docker that the Workdir differs or changing the working dir for lerna-dockerize by setting `dockerfileWorkingDir` to `/`, can fix the issue. However, changing the default from lerna-dockerize would be a breaking change. Therefore I changed the documentation to include the workdir in the base dockerfiles._
