### ISSUE TITLE
Clean install ignored in base file

### ISSUE THREAD

**Issue by cm226** [rudxde/lerna-dockerize#972]
**Describe the bug**
If I use 
RUN npm ci 
in the base docker file, the generated docker file for the base image contains 
RUN npm install

**To Reproduce**
Create a base dockerfile with 
FROM node:16-alpine3.15 as base
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci

**Expected behavior**
The generated docker file looks like 

FROM node:16-alpine3.15 as base
WORKDIR /app
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci

**Additional context**
This is a problem because the install is overwriting the package-lock.json in side the docker image. Dosnt seem to happen in the template docker files only when used in the base. Im using V1.0.1

**Comment by rudxde** [comment]
Hi, can you check if the issue is resolved in the build version `1.0.3-build.01ca83c.0`?
